---
docker_image_name: "assemragab105/carrento-backend"
docker_image_tag: "latest"
container_name: "carrento-backend"
container_port: 8000
app_env: "production"
app_debug: "false"
run_migrations: "true"
